export const GLOBAL = {
  SETTING: {
    pull_frequence: '',
    num_secoure: '',
    msg_secoure: '',
    pwd_mobile: '',
    prv_pwd_mobile: '',
  },
  ALGO_PARAMS: {
    id: '',
    temps_dechargement_typ_1: '',
    temps_marge_administration: '',
    equ_note_km_vh: '',
    equ_note_km_month_con: '',
    equ_note_km_year_con: '',
    taux_pause_in_hr_conduite: '',
    max_heur_conduite_continue: '',
    max_heur_conduite_par_jour: '',
    max_heur_conduite_semaine: '',
    max_heur_conduite_2semaine: '',
    nbr_depasse_max_jr_par_semaine: '',
    limit_depassement_max_par_j: '',
    pause_par_max_hr_conduite: '',
    equ_note_trajet_vh_imp: '',
    equ_note_trajet_con_imp: '',
    cout_affectation: '',
    max_distance_dispo_con: '',
    max_distance_dispo_vh: '',
  },
};
