export const ModulesList = {
  config: 'Configuration',
  statistic: 'Statistique',
  dispo: 'Disponibilité',
  cond: 'Gestion des chauffeurs',
  client: 'Gestion des clients',
  prest: 'Gestion des prestataires',
  pt_ctrl: 'Points de contrôle',
  vehicule: 'Gestion des véhicules',
  expedition: 'Gestion des expéditions',
  user: 'Gestion des utilisateurs',
  role: 'Gestion des rôles',
  voyage: 'Gestion des voyages',
  trajet: 'Gestion des trajets',
  reclam: 'Gestion des réclamations',
  zone: 'Gestion des zones',
  circuit: 'Gestion des circuits',
  filter: 'Gestion des combinaisons',
  validation: "Validation de sortie d'un chargement",
  plateforme: 'Gestion des plateformes',
  magasin: 'Gestion des magasins',
  quai: 'Gestion des quais',
};
