// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'Rechercher... ex.(Numéro de voyage...)':
    'Rechercher... ex.(Numéro de voyage...)',
  'Liste des voyages': 'Liste des voyages',
  'Liste des trajets': 'Liste des trajets',
  'Gestion des utilisateurs': 'Gestion des utilisateurs',
  'Gestion des clients': 'Gestion des clients',
  'Gestion des chauffeurs': 'Gestion des chauffeurs',
  'Gestion des tracteurs': 'Gestion des tracteurs',
  'Gestion des Remorques': 'Gestion des Remorques',
  'Points de contrôle': 'Points de contrôle',
  Statistiques: 'Statistiques',
  Configurations: 'Configurations',
  Déconnexion: 'Déconnexion',

  Dashboard: 'Dashboard',
  Pages: 'Pages',
  Filtre: 'Filtre',
  'Numéro du voyage ou WPT': 'Numéro du voyage ou WPT',
  'Date et heure de départ': 'Date et heure de départ',
  'Date Départ': 'Date Départ',
  'Date Arrivée': 'Date Arrivée',
  Date: 'Date',
  Statut: 'Statut',
  Complété: 'Complété',
  COMPLÉTÉ: 'COMPLÉTÉ',
  Planifié: 'Planifié',
  'En cours': 'En cours',
  'EN COURS': 'EN COURS',
  'Sans valeur': 'Sans valeur',
  'N° Chauffeur,Tracteur,Remorque': 'N° Chauffeur,Tracteur,Remorque',
  Chauffeur: 'Chauffeur',
  Tracteur: 'Tracteur',
  Remorque: 'Remorque',
  Choisir: 'Choisir',
  'Ville de Départ et Arrivée': 'Ville de Départ et Arrivée',
  'Ville Départ': 'Ville Départ',
  'Ville Arrivée': 'Ville Arrivée',

  Administrateur: 'Administrateur',
  De: 'De',
  À: 'À',
  Le: 'Le',
  PLANIFIÉ: 'PLANIFIÉ',
  Editer: 'Editer',
  Détails: 'Détails',
  Trajet: 'Trajet',
  effectué: 'effectué',
  'En attente': 'En attente',

  'Détail du voyage': 'Détail du voyage',
  'Détail du trajet': 'Détail du trajet',
  'Etat du voyage': 'Etat du voyage',
  'Etat du trajet': 'Etat du trajet',
  'Type de Voyage': 'Type de Voyage',
  Client: 'Client',
  Nature: 'Nature',
  'Agrandir la carte': 'Agrandir la carte',
  'SUIVI DU VOYAGE': 'SUIVI DU VOYAGE',
  'Nombre de WPT': 'Nombre de WPT',
  'DOCUMENTS WPT': 'DOCUMENTS WPT',
  Type: 'Type',
  Chargement: 'Chargement',
  Déchargement: 'Déchargement',
  Passage: 'Passage',
  'Liste des utilisateurs': 'Liste des utilisateurs',
  'Ajouter un utilisateur': 'Ajouter un utilisateur',
  'Recherche par matricule': 'Recherche par matricule',
  'Numéro User': 'Numéro User',
  Nom: 'Nom',
  Prénom: 'Prénom',
  Login: 'Login',
  Options: 'Options',
  Email: 'Email',
  'Liste des clients': 'Liste des clients',
  'Ajouter un client': 'Ajouter un client',
  'Numéro client': 'Numéro client',
  'Nom client': 'Nom client',
  Lier: 'Lier',
  'Recherche par nom client': 'Recherche par nom client',
  "Nom d'utilisateur": "Nom d'utilisateur",
  'Mot de passe': 'Mot de passe',
  'Se connecter': 'Se connecter',
  'Mot de passe oublié': 'Mot de passe oublié',
  'Connexion en cours': 'Connexion en cours',
  'Liste des conducteurs': 'Liste des conducteurs',
  'Ajouter un conducteur': 'Ajouter un conducteur',

  'Numéro conducteur': 'NUMERO CONDUCTOR',
  'Nom conducteur': 'Nom conducteur',
  Code: 'Code',
  'Code Département': 'Code Département',
  'Code Département Société': 'Code Département Société',
  'Recherche par nom conducteur': 'Recherche par nom conducteur',
  Supprimer: 'Supprimer',
  'Liste des tractors': 'Liste des tractors',
  'Ajouter un tractor': 'Ajouter un tractor',
  'Numéro Tractor': 'Numéro Tractor',
  Matricule: 'Matricule',
  'Liste des remorques': 'Liste des remorques',
  'Ajouter une remorque': 'Ajouter une remorque',
  'Numéro Remorque': 'Numéro Remorque',
  'Type de vehicule': 'Type de vehicule',
  'Point de contrôle': 'Point de contrôle',
  'Recherche par nom du point de contrôle':
    'Recherche par nom du point de contrôle',
  Qualification: 'Qualification',
  Photo: 'Photo',
  Description: 'Description',

  'Liste des configurations': 'Liste des configurations',
  'Fréquence de pull': 'Fréquence de pull',
  'Numéro urgence': 'Numéro urgence',
  'Message urgence': 'Message urgence',
  Enregistrer: 'Enregistrer',

  'En minutes': 'En minutes',
  "voir l'image": "voir l'image",
  Afficher: 'Afficher',
  Vitesse: 'Vitesse',

  'Modification des données du client': 'Modification des données du client',
  "Ajout d'un nouveau client": "Ajout d'un nouveau client",
  'client updated': 'client updated',
  'Le Nom client est obligatoire': 'Le Nom client est obligatoire',
  Fermer: 'Fermer',
  Close: 'Fermer',

  'Modification des données du conducteur':
    'Modification des données du conducteur',
  "Ajout d'un nouveau conducteur": "Ajout d'un nouveau conducteur",
  'conductor updated': 'conductor updated',
  'Numéro Conductor': 'Numéro Conductor',
  'Nom Conductor': 'Nom Conductor',
  'Code société': 'Code société',
  'Le login est obligatoire': 'Le login est obligatoire',

  'NOUVEAU POINT DE CONTRÔLE': 'NOUVEAU POINT DE CONTRÔLE',
  'MIS A JOUR DU POINT DE CONTRÔLE': 'MIS A JOUR DU POINT DE CONTRÔLE',
  'Données enregistrées': 'Données enregistrées',
  'Le nom du point de contrôle existe déjà':
    'Le nom du point de contrôle existe déjà',
  'Données non enregistrées': 'Données non enregistrées',
  'Nom du point de contrôle': 'Nom du point de contrôle',
  'Le Nom du point de contrôle est obligatoire':
    'Le Nom du point de contrôle est obligatoire',
  'Type de contrôle': 'Type de contrôle',
  OK: 'OK',
  'Non OK': 'Non OK',
  'Valeur(s)': 'Valeur(s)',
  'Le type de contrôle est obligatoire': 'Le type de contrôle est obligatoire',
  'Ajouter une valeur': 'Ajouter une valeur',
  'Choisir une image': 'Choisir une image',

  'Modification des données de la remorque':
    'Modification des données de la remorque',
  "Ajout d'une nouvelle remorque": "Ajout d'une nouvelle remorque",
  'Remorque updated': 'Remorque updated',
  'Le matricule ne doit pas dépasser 16 caractères':
    'Le matricule ne doit pas dépasser 16 caractères',
  successfully: 'succès',
  ERROR: 'ERREUR',
  INTERNAL_ERROR: 'Erreur interne, veuillez reessayer plus tard ! EN',
  'Type remorque': 'Type remorque',
  Longitude: 'Longitude',
  Latitude: 'Latitude',
  incorrecte: 'incorrecte',
  Exemple: 'Exemple',
  'Choisir sur la carte': 'Choisir sur la carte',

  'Modification des données du tracteur':
    'Modification des données du tracteur',
  "Ajout d'un nouveau tracteur": "Ajout d'un nouveau tracteur",
  'tractor updated': 'tractor updated',
  'Numéro Tracteur': 'Numéro Tracteur',
  "ID de l'appareil": "ID de l'appareil",
  'Incorrecte! ID doit être alphanumérique':
    'Incorrecte! ID doit être alphanumérique',

  'Modification des données du véhicule':
    'Modification des données du véhicule',
  "Ajout d'un nouveau type véhicule": "Ajout d'un nouveau type véhicule",
  'Type ajouté': 'Type ajouté',
  'Le Nom est obligatoire': 'Le Nom est obligatoire',
  Loading: 'Chargement en cours',
  TripNotStartedYet: 'Le voyage n’a pas encore démarré',

  Réclamations: 'Reclamations',

  Référence: 'Référence',
  Sélectionner: 'Sélectionner',
  Clôturée: 'Clôturée',
  'A réparer': 'A réparer',
  Emetteur: 'Emetteur',
  Document: 'Document',
  'Pas de résultats': 'Pas de résultats',
  defaultPwdMobile: 'Mot de passe par défaut',
  'En ligne': 'En ligne',
  'Hors ligne': 'Hors ligne',
  'Messages non lus': 'Messages non lus',
  'Ecrire quelque chose ...': 'Ecrire quelque chose ...',
};
