// Liste des menus pour les titre, sidebar et breadcrumb
import { ROUTES } from './routes.config';

export const MENU = [
  {
    // tableau de bord
    isMenu: true,
    parentMenu: ROUTES['dashboard'].name,
    sidebarName: 'Tableau de bord',
    routeName: ROUTES['dashboard'].name,
    icon: 'dasbord',
    icon_title: 'dasbord',
    name: 'Tableau de bord',
    role: [null],
    id_group: 14,
    children: [],
    hasBtn: false,
    target: 'read',
    header_component: null,
    style_header: null,
    isCustom: true,
  },
  {
    // Gestion des colis
    isMenu: true,
    parentMenu: ROUTES['colis'].name,
    sidebarName: 'Gestion des colis',
    routeName: ROUTES['colis'].name,
    icon: 'box',
    icon_title: 'box',
    name: 'Gestion des colis',
    role: [null],
    id_group: 14,
    children: [],
    hasBtn: false,
    header_component: 'createAddButtonComponent',
    style_header: null,
    target: 'read',
  },
  {
    // Optimisation des colis
    isMenu: false,
    parentMenu: ROUTES['colis.optimisation'].name,
    sidebarName: 'Optimisation des colis',
    routeName: ROUTES['colis.optimisation'].name,
    icon: 'driver',
    title_icon: 'driver',
    name: 'Optimisation des colis',
    role: [null],
    id_group: 14,
    children: [],
    hasBtn: false,
    header_component: 'createHeaderFilterComponent',
    style_header: 'justify-center',
    target: 'read',
  },
  {
    // Liste des tournées
    isMenu: true,
    parentMenu: ROUTES['tournees'].name,
    sidebarName: 'Tounées',
    routeName: ROUTES['tournees'].name,
    icon: 'track',
    icon_title: 'track_title',
    name: 'Liste des tournées',
    role: [null],
    id_group: 14,
    children: [],
    hasBtn: false,
    header_component: 'createAddButtonComponent',
    style_header: null,
    target: 'read',
  },
  {
    // Liste des tournée
    isMenu: false,
    parentMenu: ROUTES['tournees'].name,
    sidebarName: 'Détails Tournée',
    routeName: ROUTES['tournees.detail'].name,
    icon: 'driver',
    icon_title: 'driver',
    name: 'Détails Tournée',
    role: [null],
    id_group: 14,
    children: [],
    hasBtn: false,
    header_component: null,
    style_header: null,
    target: 'read',
  },
  {
    // vehicles list
    isMenu: true,
    parentMenu: ROUTES['vehicles'].name,
    sidebarName: 'Véhicules',
    routeName: ROUTES['vehicles'].name,
    icon: 'truck',
    icon_title: 'truck',
    name: 'Véhicules',
    role: [null],
    id_group: 14,
    children: [],
    hasBtn: false,
    header_component: null,
    style_header: null,
    target: 'read',
  },
  {
    // utilisateurs
    isMenu: true,
    parentMenu: ROUTES['utilisateurs'].name,
    sidebarName: 'Utilisateurs',
    routeName: ROUTES['utilisateurs'].name,
    icon: 'users',
    icon_title: 'users',
    name: 'Utilisateurs',
    role: [null],
    id_group: 14,
    children: [],
    hasBtn: false,
    target: 'read',
    isCustom: true,
  },
  {
    // livreurs
    isMenu: true,
    parentMenu: ROUTES['livreurs'].name,
    sidebarName: 'livreurs',
    routeName: ROUTES['livreurs'].name,
    icon: 'driver',
    icon_title: 'driver',
    name: 'livreurs',
    role: [null],
    id_group: 14,
    children: [],
    hasBtn: false,
    target: 'read',
    isCustom: true,
  },
];
