import { ERROR_MSG_500 } from './vars.config';

export const RESPONSE_CODES = {
  _400_BAD_REQUEST: {
    status: 400,
    code: '400_00',
    message: errorsMsgBykey().general.BAD_REQUEST,
    msg: 'BAD REQUEST',
  },
  _401_UNAUTHORIZED_TOKEN: {
    status: 401,
    code: '401_00',
    message: errorsMsgBykey().general.UNAUTHORIZED,
    msg: 'UNAUTHORIZED',
  },
  _500_INTERNAL_ERROR: {
    status: 500,
    code: '500_00',
    message: errorsMsgBykey().general.INTERNAL_ERROR,
    msg: 'INTERNAL ERROR',
  },
  _520_UNKNOWN_ERROR: {
    status: 520,
    code: '520_00',
    message: errorsMsgBykey().general.Unknown_Error,
    msg: 'Unknown Error',
  },
  _200_OK: { '200_00': 'OK', message: errorsMsgBykey().operation.complete },
  _404_NOT_FOUND: {
    status: 404,
    code: '404_00',
    message: errorsMsgBykey().general.Not_Found,
    msg: 'Not Found',
  },
  // user
  _404_U_NOT_FOUND: {
    status: 404,
    code: 'U404_00',
    message: errorsMsgBykey().user.not_found,
    msg: 'USER NOT_FOUND',
  },
  _409_U_EMAIL_UNIQUE: {
    status: 409,
    code: 'U409_00',
    message: errorsMsgBykey().user.no_duplicate_email,
    msg: 'USER.EMAIL UNIQUE',
  },
  _409_U_EMAIL_ACCESS_UNIQUE: {
    status: 409,
    code: 'UA409_00',
    message: errorsMsgBykey().user.no_duplicate,
    msg: 'USER ACCESS.EMAIL UNIQUE',
  },
  _200_U_LIST_OK: {
    status: 200,
    show: false,
    code: 'UL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  COM404_00: {
    status: 404,
    show: true,
    code: 'COM404_00',
    message: errorsMsgBykey().commande.not_found,
    msg: 'OK',
  },
  VOYGDEL409_00: {
    status: 409,
    show: true,
    code: 'VOYGDEL409_00',
    message: errorsMsgBykey().trip['can-not-delete'],
    msg: 'OK',
  },
  COMD409_00: {
    status: 409,
    show: true,
    code: 'COMD409_00',
    message: errorsMsgBykey().commande['COMMANDE AFFECTED'],
    msg: 'OK',
  },
  _200_AFFECTS200_00: {
    status: 200,
    show: true,
    code: 'AFFECTS200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_GET_OK: {
    status: 200,
    show: false,
    code: 'UG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_CREATE_OK: {
    status: 200,
    show: true,
    code: 'UC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'UU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_DELETE_OK: {
    status: 200,
    show: true,
    code: 'UD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_UPDATE_LANGUE_OK: {
    status: 200,
    show: true,
    code: 'UUL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_UPDATE_LANGUE_NO_ACCESS: {
    status: 500,
    code: 'UUL500_00',
    message: errorsMsgBykey().operation.NO_ACCESS_FOR_THIS_USER,
    msg: 'NO ACCESS FOR THIS USER',
  },
  _200_U_UPDATE_IMAGE_OK: {
    status: 200,
    show: true,
    code: 'UUI200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_DELETE_IMAGE_OK: {
    status: 200,
    show: true,
    code: 'UDI200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_CREATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'UCA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  GRP_DW404_00: {
    status: 404,
    show: true,
    code: 'GRP_DW404_00',
    message: errorsMsgBykey().trip.GRP_DW404_00,
    msg: 'No',
  },
  _200_VALIDER_WORKFLOW: {
    status: 200,
    show: true,
    code: 'WFC_200',
    message: errorsMsgBykey().workflow.valider,
    msg: 'OK',
  },
  _200_VALIDER_TOUT_WORKFLOW: {
    status: 200,
    show: true,
    code: 'WFCA_200',
    message: errorsMsgBykey().workflow.validerTout,
    msg: 'OK',
  },
  _200_U_UPDATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'UUA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_DELETE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'UDA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_U_PERMISSION_SYNC_OK: {
    status: 200,
    show: true,
    code: 'UP200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Auth*/
  _200_U_AUTH_OK: {
    status: 200,
    show: true,
    code: 'LIN200_00',
    message: errorsMsgBykey().auth['200'],
    msg: 'CONNECT AUTHORIZED',
  },
  _400_U_AUTH_NO_OK: {
    status: 400,
    code: 'LIN400_00',
    //  'message': errorsMsgBykey().auth["400"],
    msg: 'CONNECT NO AUTHORIZED',
  },
  _200_U_LOGOUT_OK: {
    status: 200,
    show: true,
    code: 'LOUT200_00',
    message: errorsMsgBykey().auth.DESCONNECT_OK,
    msg: 'DESCONNECT OK',
  },
  _200_U_LOGOUT_NO_OK: {
    status: 200,
    show: true,
    code: 'LOUT200_00',
    message: errorsMsgBykey().auth.DESCONNECT_ERROR,
    msg: 'DESCONNECT ERROR',
  },
  /*ROLE :*/
  _404_R_NOT_FOUND: {
    status: 404,
    code: 'R404_00',
    message: errorsMsgBykey().role.not_found,
    msg: 'ROLE NOT_FOUND',
  },
  _404_R_CLIENTS_NOT_FOUND: {
    status: 404,
    code: 'RC404_00',
    message: errorsMsgBykey().role._404_R_CLIENTS_NOT_FOUND,
    msg: 'ROLE FOR CLIENTS NOT_FOUND (Slug In.env)',
  },
  _404_R_CONDUCTEURS_NOT_FOUND: {
    status: 404,
    code: 'RCON404_00',
    message: errorsMsgBykey().role._404_R_CONDUCTEURS_NOT_FOUND,
    msg: 'ROLE FOR CHAUFFEURS NOT_FOUND (Slug In.env)',
  },
  _404_R_PRESTATAIRES_NOT_FOUND: {
    status: 404,
    code: 'RPRV404_00',
    message: errorsMsgBykey().role._404_R_PRESTATAIRES_NOT_FOUND,
    msg: 'ROLE FOR PRESTATAIRES NOT_FOUND (Slug In.env)',
  },
  _404_R_GROUPE_MODULE_NOT_FOUND_OK: {
    status: 404,
    code: 'RGM404_00',
    message: errorsMsgBykey().role._404_R_GROUPE_MODULE_NOT_FOUND_OK,
    msg: 'GROUPE MODULE NOT FOUND',
  },
  _409_R_NAME_UNIQUE: {
    status: 409,
    code: 'RN409_00',
    message: errorsMsgBykey().role.no_duplicate,
    msg: 'ROLE.NAME UNIQUE',
  },
  _200_R_LIST_OK: {
    status: 200,
    show: false,
    code: 'RL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_R_ALL_OK: {
    status: 200,
    show: false,
    code: 'RA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_R_GET_OK: {
    status: 200,
    show: false,
    code: 'RG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_R_CREATE_OK: {
    status: 200,
    show: true,
    code: 'RC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_R_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'RU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_R_DELETE_OK: {
    status: 200,
    show: true,
    code: 'RD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_R_PERMISSION_SYNC_OK: {
    status: 200,
    show: true,
    code: 'RPS200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Client :*/
  _404_C_NOT_FOUND: {
    status: 404,
    code: 'C404_00',
    message: errorsMsgBykey().client.not_found,
    msg: 'CLIENT NOT_FOUND',
  },
  _409_C_ID_UNIQUE: {
    status: 409,
    code: 'CID409_00',
    message: errorsMsgBykey().client.no_duplicate,
    msg: 'CLIENT.ID UNIQUE',
  },
  _409_C_EMAIL_UNIQUE: {
    status: 409,
    code: 'CE409_00',
    message: errorsMsgBykey().client._409_C_EMAIL_UNIQUE,
    msg: 'CLIENT.EMAIL UNIQUE',
  },
  _409_C_EMAIL_ACCESS_UNIQUE: {
    status: 409,
    code: 'CEA409_00',
    message: errorsMsgBykey().client._409_C_EMAIL_ACCESS_UNIQUE,
    msg: 'CLIENT ACCESS.EMAIL UNIQUE',
  },
  _200_C_LIST_OK: {
    status: 200,
    show: false,
    code: 'CL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_C_GET_OK: {
    status: 200,
    show: false,
    code: 'CG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_C_CREATE_OK: {
    status: 200,
    show: true,
    code: 'CC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_C_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'CU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_C_DELETE_OK: {
    status: 200,
    show: true,
    code: 'CD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_C_CREATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'CCA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_C_UPDATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'CUA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_C_DELETE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'CDA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_C_MAP_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'CMU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Conducteur - Chauffeur :*/
  _404_CON_NOT_FOUND: {
    status: 404,
    code: 'CON404_00',
    message: errorsMsgBykey().conductor.not_found,
    msg: 'CONDUCTOR NOT_FOUND',
  },
  _409_CON_ID_UNIQUE: {
    status: 409,
    code: 'CONID409_00',
    message: errorsMsgBykey().conductor.exist,
    msg: 'CONDUCTOR.ID UNIQUE',
  },
  _409_CON_EMAIL_UNIQUE: {
    status: 409,
    code: 'CONE409_00',
    message: errorsMsgBykey().conductor._409_CON_EMAIL_UNIQUE,
    msg: 'CONDUCTOR.EMAIL UNIQUE',
  },
  _409_CON_ACCESS_EMAIL_UNIQUE: {
    status: 409,
    code: 'CONEA409_00',
    message: errorsMsgBykey().conductor._409_CON_ACCESS_EMAIL_UNIQUE,
    msg: 'CONDUCTOR ACCESS.EMAIL UNIQUE',
  },
  _200_CON_LIST_OK: {
    status: 200,
    show: false,
    code: 'CONL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CON_GET_OK: {
    status: 200,
    show: false,
    code: 'CONG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CON_CREATE_OK: {
    status: 200,
    show: true,
    code: 'CONC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CON_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'CONU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CON_DELETE_OK: {
    status: 200,
    show: true,
    code: 'COND200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CON_CREATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'CONCA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CON_UPDATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'CONUA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CON_DELETE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'CONDA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*prestataire :*/
  _404_PRV_NOT_FOUND: {
    status: 404,
    code: 'PRV404_00',
    message: errorsMsgBykey().prv.not_found,
    msg: 'PRESTATAIRE NOT_FOUND',
  },
  _409_PRV_ID_UNIQUE: {
    status: 409,
    code: 'PRVID409_00',
    message: errorsMsgBykey().prv._409_PRV_ID_UNIQUE,
    msg: 'PRESTATAIRE.ID UNIQUE',
  },
  _409_PRV_EMAIL_UNIQUE: {
    status: 409,
    code: 'PRVE409_00',
    message: errorsMsgBykey().prv._409_PRV_EMAIL_UNIQUE,
    msg: 'PRESTATAIRE.EMAIL UNIQUE',
  },
  _409_PRV_ACCESS_EMAIL_UNIQUE: {
    status: 409,
    code: 'PRVEA409_00',
    message: errorsMsgBykey().prv._409_PRV_ACCESS_EMAIL_UNIQUE,
    msg: 'PRESTATAIRE ACCESS.EMAIL UNIQUE',
  },
  _200_PRV_LIST_OK: {
    status: 200,
    show: false,
    code: 'PRVL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PRV_GET_OK: {
    status: 200,
    show: false,
    code: 'PRVG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PRV_CREATE_OK: {
    status: 200,
    show: true,
    code: 'PRVC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PRV_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'PRVU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PRV_DELETE_OK: {
    status: 200,
    show: true,
    code: 'PRVD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PRV_CREATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'PRVCA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PRV_UPDATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'PRVUA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PRV_DELETE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'PRVDA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*zones :*/
  _200_Z_LIST_OK: {
    status: 200,
    code: 'ZL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_Z_CREATE_OK: {
    status: 200,
    code: 'ZC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_Z_UPDATE_OK: {
    status: 200,
    code: 'ZU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Vehicule :*/
  _404_VH_NOT_FOUND: {
    status: 404,
    code: 'VH404_00',
    message: errorsMsgBykey().vehicule.not_found,
    msg: 'VEHICULE NOT_FOUND',
  },
  _409_VH_ID_UNIQUE: {
    status: 409,
    code: 'VHID409_00',
    message: errorsMsgBykey().vehicule.unique_code,
    msg: 'VEHICULE.ID UNIQUE',
  },
  _409_VH_MATRICULE_UNIQUE: {
    status: 409,
    code: 'VHM409_00',
    message: errorsMsgBykey().vehicule.unique_mat,
    msg: 'VEHICULE.MATRICULE UNIQUE',
  },
  _200_VH_LIST_OK: {
    status: 200,
    show: false,
    code: 'VHL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_VH_GET_OK: {
    status: 200,
    show: false,
    code: 'VHG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_VH_CREATE_OK: {
    status: 200,
    show: true,
    code: 'VHC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_VH_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'VHU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_VH_DELETE_OK: {
    status: 200,
    show: true,
    code: 'VHD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_VH_ATTACH_ADD_OK: {
    status: 200,
    show: true,
    code: 'VHAADD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_VH_ATTACH_RM_OK: {
    status: 200,
    show: true,
    code: 'VHDARM200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_VH_ATTACH_ORDER_OK: {
    status: 200,
    show: true,
    code: 'VHDAORD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Type deplacement :*/
  _404_TDEP_NOT_FOUND: {
    status: 404,
    code: 'TDEP404_00',
    message: errorsMsgBykey().deplacement.not_found,
    msg: 'TYPE DEPLACEMENT NOT_FOUND',
  },
  /*Type Vehicule :*/
  _404_TVH_NOT_FOUND: {
    status: 404,
    code: 'TVH404_00',
    message: errorsMsgBykey().vehicule.type_not_found,
    msg: 'TYPE VEHICULE NOT_FOUND',
  },
  _409_TVH_TYPE_NAME_UNIQUE: {
    status: 409,
    code: 'TVHT409_00',
    message: errorsMsgBykey().vehicule.unique_type,
    msg: 'TYPE  VEHICULE.Type UNIQUE',
  },
  _200_TVH_LIST_OK: {
    status: 200,
    show: false,
    code: 'TVHL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TVH_GET_OK: {
    status: 200,
    show: false,
    code: 'TVHG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TVH_CREATE_OK: {
    status: 200,
    show: true,
    code: 'TVHC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TVH_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'TVHU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TVH_DELETE_OK: {
    status: 200,
    show: true,
    code: 'TVHD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Point Controle :*/
  _404_PT_CTRL_NOT_FOUND: {
    status: 404,
    code: 'PT404_00',
    message: errorsMsgBykey().point.not_found,
    msg: 'POINT CONTROLE NOT_FOUND',
  },
  _409_PT_CTRL_NAME_UNIQUE: {
    status: 409,
    code: 'PTT409_00',
    message: errorsMsgBykey().point.unique,
    msg: 'POINT CONTROLE.NAME UNIQUE',
  },
  _200_PT_CTRL_LIST_OK: {
    status: 200,
    show: false,
    code: 'PTL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PT_CTRL_GET_OK: {
    status: 200,
    show: false,
    code: 'PTG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PT_CTRL_CREATE_OK: {
    status: 200,
    show: true,
    code: 'PTC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PT_CTRL_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'PTU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PT_CTRL_DELETE_OK: {
    status: 200,
    show: true,
    code: 'PTD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_PT_CTRL_REMOVE_PHOTO_OK: {
    status: 200,
    show: true,
    code: 'PTRPH200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Magasin :*/
  _404_M_NOT_FOUND: {
    status: 404,
    code: 'M404_00',
    message: errorsMsgBykey().magasin.not_found,
    msg: 'MAGASIN NOT_FOUND',
  },
  _409_M_ID_UNIQUE: {
    status: 409,
    code: 'MID409_00',
    message: errorsMsgBykey().magasin.unique,
    msg: 'MAGASIN.ID UNIQUE',
  },
  _200_M_LIST_OK: {
    status: 200,
    show: false,
    code: 'ML200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_M_GET_OK: {
    status: 200,
    show: false,
    code: 'MG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_M_CREATE_OK: {
    status: 200,
    show: true,
    code: 'MC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_M_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'MU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_M_DELETE_OK: {
    status: 200,
    show: true,
    code: 'MD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_M_CREATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'MCA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_M_UPDATE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'MUA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_M_DELETE_ACCESS_OK: {
    status: 200,
    show: true,
    code: 'MDA200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_M_MAP_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'MUM200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Plateforme*/
  _404_PF_NOT_FOUND: {
    status: 404,
    code: 'M404_00',
    message: errorsMsgBykey().plateforme.not_found,
    msg: 'PLATEFORME NOT_FOUND',
  },
  _200_PF_CREATE_OK: {
    status: 200,
    show: true,
    code: 'PF200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Quai*/
  _404_Q_NOT_FOUND: {
    status: 404,
    code: 'Q404_00',
    show: true,
    message: errorsMsgBykey().quai.not_found,
    msg: 'QUAI NOT_FOUND',
  },
  _409_Q_ID_UNIQUE: {
    status: 409,
    code: 'QID409_00',
    show: true,
    message: errorsMsgBykey().quai.unique,
    msg: 'QUAI NOT_FOUND',
  },
  _200_Q_CREATE_OK: {
    status: 200,
    show: true,
    code: 'QC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_Q_DELETE_OK: {
    status: 200,
    show: true,
    code: 'QD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },

  _200_Q_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'QC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },

  /*DayWork*/
  _200_DW_SYNC_OK: {
    status: 200,
    show: true,
    code: 'DW200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Ville :*/
  _404_V_NOT_FOUND: {
    status: 404,
    code: 'V404_00',
    message: errorsMsgBykey().ville.not_found,
    msg: 'VILLE NOT_FOUND',
  },
  /*produit :*/
  _404_P_NOT_FOUND: {
    status: 404,
    code: 'P404_00',
    message: errorsMsgBykey().produit.not_found,
    msg: 'PRODUIT NOT_FOUND',
  },
  _409_P_ID_UNIQUE: {
    status: 409,
    code: 'PID409_00',
    message: errorsMsgBykey().produit.unique,
    msg: 'PRODUIT.ID UNIQUE',
  },
  _409_P_DESIGNATION_UNIQUE: {
    status: 409,
    code: 'PD409_00',
    message: errorsMsgBykey().produit.uniqu_des,
    msg: 'PRODUIT.DESIGNATION UNIQUE',
  },
  /*Commande :*/
  _404_COM_NOT_FOUND: {
    status: 404,
    code: 'COM404_00',
    message: errorsMsgBykey().commande.not_found,
    msg: 'COMMANDE NOT_FOUND',
  },
  _200_COM_LIST_OK: {
    status: 200,
    show: false,
    code: 'COML200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_COM_GET_OK: {
    status: 200,
    show: false,
    code: 'COMG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_P_LIST_OK: {
    status: 200,
    show: false,
    code: 'PL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_P_GET_OK: {
    status: 200,
    show: false,
    code: 'PG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_P_CREATE_OK: {
    status: 200,
    show: true,
    code: 'PC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_P_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'PU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_P_DELETE_OK: {
    status: 200,
    show: true,
    code: 'PD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Reclamation :*/
  _404_RC_NOT_FOUND: {
    status: 404,
    code: 'RC404_00',
    message: errorsMsgBykey().reclamation.not_found,
    msg: 'RECLAMATION NOT_FOUND',
  },
  _200_RC_LIST_OK: {
    status: 200,
    show: false,
    code: 'RCL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_RC_GET_OK: {
    status: 200,
    show: false,
    code: 'RCG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_RC_CREATE_OK: {
    status: 200,
    show: true,
    code: 'RCC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_RC_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'RCU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_RC_DELETE_OK: {
    status: 200,
    show: true,
    code: 'RCD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_RC_DOC_CREATE_OK: {
    status: 200,
    show: true,
    code: 'RCDC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _404_RC_DOC_NOT_FOUND: {
    status: 404,
    code: 'RCD404_00',
    message: errorsMsgBykey().reclamation.doc_not_found,
    msg: 'DOCUMENT RECLAMATION NOT_FOUND',
  },
  _200_RC_DOC_DELETE_OK: {
    status: 200,
    show: true,
    code: 'RCDD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Type reclamation :*/
  _404_TRC_NOT_FOUND: {
    status: 404,
    code: 'TRC404_00',
    message: errorsMsgBykey().reclamation.type_not_found,
    msg: 'TYPE RECLAMATION NOT_FOUND',
  },
  _409_TRC_TYPE_UNIQUE: {
    status: 409,
    code: 'TRCT409_00',
    message: errorsMsgBykey().reclamation.unique,
    msg: 'TYPE RECLAMATION NAME UNIQUE',
  },
  _200_TRC_LIST_OK: {
    status: 200,
    show: false,
    code: 'TRCL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TRC_GET_OK: {
    status: 200,
    show: false,
    code: 'TRCG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TRC_CREATE_OK: {
    status: 200,
    show: true,
    code: 'TRCC200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TRC_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'TRCU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TRC_DELETE_OK: {
    status: 200,
    show: true,
    code: 'TRCD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Configuration :*/

  CONFIG_UPDATE_PLANIF_SUCCESS_200: {
    status: 200,
    show: true,
    code: 'CONFIG_UPDATE_PLANIF_SUCCESS_200',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },

  CONFIG_UPDATE_CONDUITE_SUCCESS_200: {
    status: 200,
    show: true,
    code: 'CONFIG_UPDATE_CONDUITE_SUCCESS_200',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },

  PONDER_CONFIG_SUCCES_200: {
    status: 200,
    show: true,
    code: 'PONDER_CONFIG_SUCCES_200',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },

  TARIF_CONFIG_SUCCES_200: {
    status: 200,
    show: true,
    code: 'TARIF_CONFIG_SUCCES_200',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },

  _200_CONFIG_GET_OK: {
    status: 200,
    show: false,
    code: 'CONFG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CONFIG_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'CONFU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CONFIG_AFFECT_GET_OK: {
    status: 200,
    show: false,
    code: 'CONFAG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CONFIG_AFFECT_OBJ_NOT_FOUND: {
    status: 200,
    show: true,
    code: 'CONFAOBJ404_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_CONFIG_AFFECT_UPDATE_OK: {
    status: 200,
    show: true,
    code: 'CONFAU200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*Trajet :*/
  _200_TRAJET_LIST_OK: {
    status: 200,
    show: false,
    code: 'TRAL200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _200_TRAJET_GET_OK: {
    status: 200,
    show: false,
    code: 'TRAG200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  _404_TRAJET_NOT_FOUND: {
    status: 404,
    code: 'TRA404_00',
    message: errorsMsgBykey().trajet.not_found,
    msg: 'TRAJET NOT_FOUND',
  },
  _404_TRAJET_COMMANDES_NONE: {
    status: 404,
    code: 'TRAC404_00',
    message: errorsMsgBykey().trajet.deleted_commandes,
    msg: 'TRAJET HAS MANUALLY DELETED COMMANDES',
  },
  /*Mobile :*/
  _200_mobile_demo_GET_OK: {
    status: 200,
    show: false,
    code: 'MOBILEDEMO200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  COMD200_00: {
    status: 200,
    show: true,
    code: 'COMD200_00',
    message: errorsMsgBykey().operation.complete,
    msg: 'OK',
  },
  /*voyage :*/
  _404_VOYAGE_NOT_FOUND: {
    status: 404,
    code: 'VOY404_00',
    message: errorsMsgBykey().trip.not_found,
    msg: 'VOYAGE NOT_FOUND',
  },
  _404_VOYAGE_COMMANDES_NONE: {
    status: 404,
    code: 'VOYC404_00',
    message: errorsMsgBykey().trip.deleted_commandes,
    msg: 'VOYAGE HAS MANUALLY DELETED COMMANDES',
  },
  VOYGDEL200_00: {
    status: 200,
    show: true,
    code: 'VOYGDEL200_00',
    message: errorsMsgBykey().operation.complete,
  },
  _200_VOYAGE_LIST_OK: {
    status: 200,
    show: false,
    code: 'VOYL200_00',
    message: errorsMsgBykey().operation.complete,
  },
  _200_VOYAGE_GET_OK: {
    status: 200,
    show: false,
    code: 'VOYG200_00',
    message: errorsMsgBykey().operation.complete,
  },

  _404_U_STATUS_NOT_VALID: {
    status: 400,
    show: true,
    code: 'UINV404_00',
    message: errorsMsgBykey().operation.noneToUpdate,
  },
  _404_PT_CTRL_NOT_VALID: {
    status: 400,
    show: true,
    code: 'PCINV404_00',
    message: errorsMsgBykey().trip.PT_CTRL_NOT_VALID,
  },
  _200_U_STATUS: {
    status: 200,
    show: true,
    code: 'UST200_00',
    message: errorsMsgBykey().operation.complete,
  },

  /* filtre dynamique */
  F_CREATE_200_02: {
    status: 200,
    show: true,
    code: 'F200_02',
    message: errorsMsgBykey().combinaison.create,
  },
  F_UPDATE_200_03: {
    status: 200,
    show: true,
    code: 'F200_03',
    message: errorsMsgBykey().combinaison.update,
  },
  F_LISTED_200_00: {
    status: 200,
    show: false,
    code: 'F200_00',
    message: errorsMsgBykey().operation.complete,
  },
  F_ACTIVE_STATUS_200_05: {
    status: 200,
    show: true,
    code: 'F200_05',
    message: errorsMsgBykey().combinaison.activated,
  },
  F_DEACTIVE_STATUS_200_06: {
    status: 200,
    show: true,
    code: 'F200_06',
    message: errorsMsgBykey().combinaison.deactivated,
  },
  F_EMPTY_400_07: {
    status: 400,
    show: true,
    code: 'F200_07',
    message: errorsMsgBykey().combinaison.not_validate,
  },
  F_ALREADY_CREATED_400_02: {
    status: 400,
    show: true,
    code: 'F400_02',
    message: errorsMsgBykey().combinaison.exist,
  },
};

export function errorsMsgBykey(lang = null) {
  switch (lang) {
    case 'es':
      return {
        operation: {
          incomplete: 'La operación incompleta',
          complete: 'La operación se realizó con éxito',
          noneToUpdate: 'La operación incompleta, nada para modificar.',
          success_update: 'El cambio es exitoso.',
          NO_ACCESS_FOR_THIS_USER: "Cet utilisateur n'a pas d'accès",
        },
        client: {
          create: 'El cliente crea con éxito.',
          update: 'El Cliente modificado con éxito.',
          delete: 'El Cliente eliminado con éxito.',
          exist: 'El cliente existe !',
          not_found: 'El Cliente no encontrado !',
          _409_C_EMAIL_UNIQUE: 'Client email doit être unique',
          _409_C_EMAIL_ACCESS_UNIQUE: "Client email d'accès doit être unique",
          no_duplicate: 'El login debe ser único.',
          perm_workflow_exist:
            'Permiso de cliente de flujo de trabajo ya asignado !',
          perm_workflow_not_exist:
            'permiso de cliente de flujo de trabajo no asignado !',
        },
        prv: {
          create: 'El proveedor crea con éxito.',
          update: 'El proveedor modificado con éxito.',
          delete: 'El proveedor eliminado con éxito.',
          exist: 'El proveedor existe !',
          not_found: 'El proveedor no encontrado !',
          no_duplicate: 'El login debe ser único.',
          _409_PRV_ID_UNIQUE: 'Prestataire code doit être unique !',
          _409_PRV_EMAIL_UNIQUE: 'Prestataire email doit être unique !',
          _409_PRV_ACCESS_EMAIL_UNIQUE:
            "Prestataire email d'accès doit être unique !",
        },
        conductor: {
          create: 'El conductor crea con éxito.',
          update: 'El conductor modificado con éxito.',
          delete: 'El conductor eliminado con éxito.',
          exist: 'El conductor existe !',
          not_found: 'El conductor no encontrado !',
          _409_CON_EMAIL_UNIQUE: 'Conducteur email doit être unique',
          _409_CON_ACCESS_EMAIL_UNIQUE:
            "Conducteur email d'accès doit être unique",
        },
        line: {
          not_found: 'El línea no encontrada !',
          is_planif: 'El Viaje ya planeado !',
          no_resource: 'No recursos conductores, tractores o remolques.',
        },
        trip: {
          not_found: 'El viaje no encontrada !',
          'can-not-delete':
            'Vous ne pouvez pas supprimer une voyage ayant une statut en cours ou une statut terminée',
          GRP_DW404_00:
            "Veuillez vérifier les heures d'ouvertures des magasins sélectionnés.",
        },
        ville: {
          not_found: 'Ville introuvable !',
        },
        trajet: {
          not_found: 'Trajet introuvable !',
        },
        commande: {
          not_found: 'Commande introuvable !',
          'COMMANDE AFFECTED': 'commande est affecté',
        },
        deplacement: {
          not_found: 'Type deplacement introuvable !',
        },
        file: {
          delete: 'El documento fue eliminado exitosamente.',
          error: 'Error al descargar el documento.',
          not_found: 'Documento no encontrado !',
          error_extension:
            'Seleccione una imagen (extensión: png, gif, jpeg, jpg).',
        },
        point: {
          not_found: 'Punto no encontrado !',
          unique: 'Point contrôle doit être unique !',
        },
        magasin: {
          not_found: 'Magasin introuvable !',
          unique: 'Magasin doit être unique !',
        },
        produit: {
          not_found: 'Produit introuvable !',
          unique: 'Produit doit être unique !',
          uniqu_des: 'Produit designation doit être unique !',
        },
        workflow: {
          create: 'El flujo de trabajo crea con éxito.',
          incomplete_origin: 'Flujos de trabajo de punto de origen incompleto!',
          exist:
            'Flujo de trabajo ya creado (prioridad de la aplicación móvil).',
          valider: 'Workflow validé avec succès',
          validerTout: 'Tous les workflows sont validés avec succès',
        },
        reclamation: {
          not_found: 'Reclamacion no encontrado !',
          doc_not_found: 'document de reclamation introuvable !',
          type_not_found: 'type de reclamation introuvable !',
          unique: 'Nom de type de reclamation doit être unique !',
        },
        remorque: {
          create: 'El remolque crea con éxito.',
          update: 'El remolque modificado con éxito.',
          delete: 'El remolque eliminado con éxito.',
          exist: 'El remolque existe !',
          not_found: 'El remolque no encontrado !',
        },
        vehicule: {
          create: 'Véhicule créée avec succès.',
          update: 'Véhicule modifiée avec succès.',
          delete: 'Véhicule supprimé avec succès.',
          exist: 'Véhicule exist !',
          not_found: 'Véhicule introuvable !',
          type_not_found: 'Type véhicule introuvable !',
          unique_type: 'Véhicule type doit être unique !',
          unique_code: 'Véhicule code doit être unique !',
          unique_mat: 'Véhicule matricule doit être unique !',
        },
        sr_control: {
          no_duplicate: 'El nombre del punto de control debe ser único.',
          create: 'El Punto de control crea con éxito.',
          update: 'El Punto de control modificado con éxito.',
          delete: 'El Punto de control eliminado con éxito.',
          img_delete: 'imagen del Punto de control eliminado con éxito.',
          exist: 'El Punto de control existe !',
          not_found: 'El Punto de control no encontrado !',
        },
        tractor: {
          create: 'El tractor crea con éxito.',
          update: 'El tractor modificado con éxito.',
          delete: 'El tractor eliminado con éxito.',
          exist: 'El tractor existe !',
          not_found: 'El tractor no encontrado !',
        },
        type_vh: {
          no_duplicate: 'El nombre del tipo de vehículo debe ser único.',
          create: 'El tipo de vehículo crea con éxito.',
          update: 'El tipo de vehículo modificado con éxito.',
          delete: 'El tipo de vehículo eliminado con éxito.',
          exist: 'El tipo de vehículo existe !',
          not_found: 'El tipo de vehículo no encontrado !',
          required_ctrl_id: 'El campo ctrl_id es requerido para esta acción.',
          required_ctrl_ids_arr:
            'El campo ctrl_ids_arr es requerido para esta acción.',
        },
        user: {
          create: 'El usuario crea con éxito.',
          update: 'El usuario modificado con éxito.',
          delete: 'El usuario eliminado con éxito.',
          exist: 'Usuario existe !',
          not_found: 'Usuario no encontrado !',
          no_duplicate: 'El login debe ser único.',
          no_duplicate_email: 'El correo electrónico debe ser único.',
          setting_update: 'Cambiar la configuración realizada con éxito.',
          langage_update: 'Modificación de idioma realizada con éxito.',
          no_update_super_admin: 'Sin cambios para el usuario de super admin.',
        },
        auth: {
          '500': 'Inicio de sesión o contraseña incorrecta.',
          '200': 'Conexión exitosa.',
          '403': 'Debe tener una autorización.',
          no_permissions: 'Debes tener permisos.',
          DESCONNECT_OK: 'Déconnexion avec succes',
          DESCONNECT_ERROR: 'Echec de logout',
        },
        role: {
          create: 'El rol se crea con éxito.',
          update: 'El rol modificado con éxito.',
          delete: 'El rol eliminado con éxito.',
          exist: 'El rol existe.',
          not_found: 'El Rol no encontrado.',
          _404_R_CLIENTS_NOT_FOUND: 'rôle du clients introuvable !',
          _404_R_CONDUCTEURS_NOT_FOUND: 'rôle du chauffeurs introuvable !',
          _404_R_PRESTATAIRES_NOT_FOUND: 'rôle du prestataires introuvable !',
          _404_R_GROUPE_MODULE_NOT_FOUND_OK: 'group introuvable !',
          no_duplicate: 'El nombre de la función debe ser único.',
          no_update_super_admin:
            'Sin cambios para el rol de super administrador.',
          no_update_client: 'Sin cambios para el rol del cliente.',
          no_update_prestataire: 'Sin cambios para el rol del servicio.',
        },
        permission: {
          not_validate:
            'Los permisos (Leer, Cambiar, Eliminar) con los valores 0 o 1 deben estar en la lista (111,110,100,000).',
          not_found: 'Permiso no encontrado',
        },
        group_module: {
          not_found: 'Módulo intrusivo.',
        },
        general: {
          BAD_REQUEST: 'Format invalide',
          UNAUTHORIZED: 'Login incorrect',
          INTERNAL_ERROR: ERROR_MSG_500,
          Unknown_Error: 'Erreur de serveur !',
          Not_Found: 'Introuvable !',
        },
      };
    default: //fr
      return {
        operation: {
          incomplete: 'Opération incomplète !',
          complete: 'Opération terminée avec succès.',
          noneToUpdate: 'Opération incomplète, rien a modifier.',
          success_update: 'La modification fait avec succès',
          NO_ACCESS_FOR_THIS_USER: "Cet utilisateur n'a pas d'accès",
        },
        client: {
          create: 'Client créé avec succès.',
          update: 'Client modifiée avec succès.',
          delete: 'Client supprimé avec succès.',
          exist: 'Client exist !',
          not_found: 'Client introuvable !',
          _409_C_EMAIL_UNIQUE: 'Client email doit être unique',
          _409_C_EMAIL_ACCESS_UNIQUE: "Client email d'accès doit être unique",
          no_duplicate: 'Login doit être unique.',
          perm_workflow_exist: 'Permission Client workflow déja affecté !',
          perm_workflow_not_exist: 'Permission Client workflow non affecté !',
        },
        prv: {
          create: 'Prestataire créé avec succès.',
          update: 'Prestataire modifiée avec succès.',
          delete: 'Prestataire supprimé avec succès.',
          exist: 'Prestataire exist !',
          not_found: 'Prestataire introuvable !',
          no_duplicate: 'Login doit être unique.',
          _409_PRV_ID_UNIQUE: 'Prestataire code doit être unique !',
          _409_PRV_EMAIL_UNIQUE: 'Prestataire email doit être unique !',
          _409_PRV_ACCESS_EMAIL_UNIQUE:
            "Prestataire email d'accès doit être unique !",
        },
        conductor: {
          create: 'Conducteur créé avec succès.',
          update: 'Conducteur modifiée avec succès.',
          delete: 'Conducteur supprimé avec succès.',
          exist: 'Conducteur exist !.',
          not_found: 'Conducteur introuvable !',
          _409_CON_EMAIL_UNIQUE: 'Conducteur email doit être unique',
          _409_CON_ACCESS_EMAIL_UNIQUE:
            "Conducteur email d'accès doit être unique",
        },
        line: {
          not_found: 'Trajet introuvable !',
          is_planif: 'Trajet déja planifiée !',
          no_resource: 'Pas de resources conducteurs, tracteurs ou remorques.',
        },
        trip: {
          not_found: 'Voyage introuvable !',
          'can-not-delete':
            'Vous ne pouvez pas supprimer un voyage en cours ou un voyage terminée',
          GRP_DW404_00:
            "Veuillez vérifier les heures d'ouvertures des magasins sélectionnés.",
          deleted_commandes:
            'Des commandes de ce voyage sont suprimées manuellement !',
          status_not_valid:
            "Vous ne pouvez pas valider la sortie d'un voyage non approuvé ou un voyage en cours ",
          PT_CTRL_NOT_VALID:
            "Vous ne pouvez pas valider la sortie d'un voyage avant la validation des points de contrôle",
        },
        ville: {
          not_found: 'Ville introuvable !',
        },
        trajet: {
          not_found: 'Trajet introuvable !',
          deleted_commandes:
            'Des commandes de ce trajet sont suprimées manuellement !',
        },
        commande: {
          not_found: 'Commande introuvable !',
          'COMMANDE AFFECTED': 'commande est affecté',
        },
        deplacement: {
          not_found: 'Type deplacement introuvable !',
        },
        file: {
          delete: 'Le document supprimée avec succès.',
          error: 'Erreur téléchargement de document.',
          not_found: 'Document introuvable !',
          error_extension:
            'Selectionner une image (extension: png,gif, jpeg, jpg).',
        },
        point: {
          not_found: 'Point introuvable !',
          unique: 'Point contrôle doit être unique !',
        },
        magasin: {
          not_found: 'Magasin introuvable !',
          unique: 'Magasin doit être unique !',
        },
        plateforme: {
          not_found: 'Plateforme introuvable !',
          unique: 'Magasin doit être unique !',
        },
        quai: {
          not_found: 'Quai introuvable !',
          unique: 'Quai doit être unique !',
        },
        produit: {
          not_found: 'Produit introuvable !',
          unique: 'Produit doit être unique !',
          uniqu_des: 'Produit designation doit être unique !',
        },
        workflow: {
          create: 'Workflow créé avec succès.',
          incomplete_origin: "Workflows de point d'origin incomplete !",
          exist: 'Workflow déja créé ( priorité application mobile ).',
          valider: 'Workflow validé avec succès',
          validerTout: 'Tous les workflows sont validés avec succès',
        },
        reclamation: {
          not_found: 'Reclamation introuvable !',
          doc_not_found: 'document de reclamation introuvable !',
          type_not_found: 'type de reclamation introuvable !',
          unique: 'Nom de type de reclamation doit être unique !',
        },
        remorque: {
          create: 'Remorque créée avec succès.',
          update: 'Remorque modifiée avec succès.',
          delete: 'Remorque supprimé avec succès.',
          exist: 'Remorque exist !',
          not_found: 'Remorque introuvable !',
        },
        vehicule: {
          create: 'Véhicule créée avec succès.',
          update: 'Véhicule modifiée avec succès.',
          delete: 'Véhicule supprimé avec succès.',
          exist: 'Véhicule exist !',
          not_found: 'Véhicule introuvable !',
          type_not_found: 'Type véhicule introuvable !',
          unique_type: 'Véhicule type doit être unique !',
          unique_code: 'Véhicule code doit être unique !',
          unique_mat: 'Véhicule matricule doit être unique !',
        },
        sr_control: {
          no_duplicate: 'Nom de Point de contrôle doit être unique.',
          create: 'Point de controle créé avec succès.',
          update: 'Point de controle modifiée avec succès.',
          delete: 'Point de controle supprimé avec succès.',
          img_delete: 'Image de Point de controle supprimé avec succès.',
          exist: 'Point de controle exist !',
          not_found: 'Point de controle introuvable !',
        },
        tractor: {
          create: 'Tracteur créé avec succès.',
          update: 'Tracteur modifiée avec succès.',
          delete: 'Tracteur supprimé avec succès.',
          exist: 'Tracteur exist !',
          not_found: 'Tracteur introuvable !',
        },
        type_vh: {
          no_duplicate: 'Nom de type vehicule doit être unique.',
          create: 'Type de vehicule créé avec succès.',
          update: 'Type de vehicule modifiée avec succès.',
          delete: 'Type de vehicule supprimé avec succès.',
          exist: 'Type de vehicule exist !',
          not_found: 'Type de vehicule introuvable !',
          required_ctrl_id:
            'Le champ ctrl_id est obligatoire pour cette action.',
          required_ctrl_ids_arr:
            'Le champ ctrl_ids_arr est obligatoire pour cette action.',
        },
        user: {
          create: 'Utilisateur créé avec succès.',
          update: 'Utilisateur modifiée avec succès.',
          delete: 'Utilisateur supprimé avec succès.',
          exist: 'Utilisateur exist !',
          not_found: 'Utilisateur introuvable !',
          no_duplicate: 'Login doit être unique.',
          no_duplicate_email: 'Email doit être unique.',
          setting_update: 'Modification des paramètres fait avec succès.',
          langage_update: 'Modification de langage fait avec succès.',
          no_update_super_admin:
            'Pas de modification pour un utilisateur super admin.',
        },
        auth: {
          '400': 'Login ou mot de passe incorrects.',
          '200': 'Connexion réussie.',
          '403': "Vous devez disposer d'une autorisation.",
          no_permissions: 'Vous devez disposer des permissions.',
          DESCONNECT_OK: 'Déconnexion avec succes',
          DESCONNECT_ERROR: 'Echec de logout',
        },
        role: {
          create: 'Role créé avec succès.',
          update: 'Role modifiée avec succès.',
          delete: 'Role supprimé avec succès.',
          exist: 'Role exist !',
          not_found: 'Role introuvable !',
          _404_R_CLIENTS_NOT_FOUND: 'rôle du clients introuvable !',
          _404_R_CONDUCTEURS_NOT_FOUND: 'rôle du chauffeurs introuvable !',
          _404_R_PRESTATAIRES_NOT_FOUND: 'rôle du prestataires introuvable !',
          _404_R_GROUPE_MODULE_NOT_FOUND_OK: 'group introuvable !',
          no_duplicate: 'Nom de Role doit être unique.',
          no_update_super_admin:
            'Pas de modification pour le role super administrateur.',
          no_update_client: 'Pas de modification pour le role client.',
          no_update_prestataire:
            'Pas de modification pour le role prestataire.',
        },
        permission: {
          not_validate:
            'Permissions (Lecture,Modification,Suppression) avec valeurs 0 ou 1 doit etre dans la list (111,110,100,000).',
          not_found: 'Permission introuvable',
        },
        group_module: {
          not_found: 'Module introuvable !',
        },
        general: {
          BAD_REQUEST: 'Format invalide',
          UNAUTHORIZED: 'Login incorrect',
          INTERNAL_ERROR: ERROR_MSG_500,
          Unknown_Error: 'Erreur de serveur !',
          Not_Found: 'Introuvable !',
        },
        combinaison: {
          create: 'Combinaison créée avec succès.',
          update: 'Combinaison modifiée avec succès.',
          activated: 'Combinaison activé avec succès.',
          deactivated: 'Combinaison désactivé avec succès.',
          not_validate: "aucun filtre n'a été selectionné",
          exist: 'Conducteur exist !.',
        },
      };
  }
}
